/**
 * W3C ``eddsa-jcs-2022`` Data Integrity proof verification.
 *
 * A cross-language twin of `libagentweb.signing` in Python: same canonical-
 * ization (RFC 8785 JCS), same signing input (SHA-256 of canonical proof
 * options followed by SHA-256 of the canonical unsigned document), same
 * Multikey decoding, and same rejection reasons. Byte-level agreement with
 * the Python implementation is enforced by the committed conformance vectors
 * in `src/vectors/data-integrity.vectors.json`, which are generated by
 * `scripts/generate_data_integrity_vectors.py`.
 */

import { createHash, createPublicKey, verify as nodeVerify } from "node:crypto";

const BASE58_ALPHABET =
  "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

export class ProofVerificationError extends Error {}

export interface ProofVerificationMethod {
  id: string;
  type: string;
  controller: string;
  publicKeyMultibase: string;
}

export interface ProofControllerDocument {
  verificationMethod?: ProofVerificationMethod[];
  assertionMethod?: Array<string | { id?: string }>;
}

export interface DataIntegrityProof {
  type: string;
  cryptosuite: string;
  verificationMethod: string;
  proofPurpose: string;
  created: string;
  proofValue: string;
  [key: string]: unknown;
}

/**
 * RFC 8785 JSON Canonicalization Scheme.
 *
 * Object keys are sorted by UTF-16 code unit order and serialized with
 * ECMAScript `JSON.stringify`, whose string escaping and shortest-round-trip
 * number formatting are exactly what JCS mandates.
 */
export function jcsCanonicalize(value: unknown): string {
  if (
    value === null ||
    typeof value === "boolean" ||
    typeof value === "number" ||
    typeof value === "string"
  ) {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(jcsCanonicalize).join(",")}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, member]) => member !== undefined,
    );
    entries.sort(([left], [right]) =>
      left < right ? -1 : left > right ? 1 : 0,
    );
    return `{${entries
      .map(([key, member]) => `${JSON.stringify(key)}:${jcsCanonicalize(member)}`)
      .join(",")}}`;
  }
  throw new TypeError("JCS input must be JSON-representable data");
}

function base58Decode(value: string): Buffer {
  const bytes: number[] = [];
  for (const character of value) {
    const alphabetIndex = BASE58_ALPHABET.indexOf(character);
    if (alphabetIndex < 0) {
      throw new Error(`invalid base58 character: ${character}`);
    }
    let carry = alphabetIndex;
    for (let index = 0; index < bytes.length; index += 1) {
      carry += bytes[index] * 58;
      bytes[index] = carry & 0xff;
      carry >>= 8;
    }
    while (carry > 0) {
      bytes.push(carry & 0xff);
      carry >>= 8;
    }
  }
  let zeros = 0;
  for (const character of value) {
    if (character === "1") zeros += 1;
    else break;
  }
  bytes.reverse();
  return Buffer.concat([Buffer.alloc(zeros), Buffer.from(bytes)]);
}

/** Decode an Ed25519 Multikey (`z` multibase, multicodec 0xed01). */
export function multikeyToPublicKey(multibase: string) {
  if (!multibase.startsWith("z")) {
    throw new Error("verification Multikey must use the z multibase");
  }
  let encoded: Buffer;
  try {
    encoded = base58Decode(multibase.slice(1));
  } catch {
    throw new Error("verification Multikey is not valid base58-btc");
  }
  if (encoded.length !== 34 || encoded[0] !== 0xed || encoded[1] !== 0x01) {
    throw new Error("verification Multikey is not Ed25519");
  }
  const spki = Buffer.concat([
    Buffer.from("302a300506032b6570032100", "hex"),
    encoded.subarray(2),
  ]);
  return createPublicKey({ key: spki, format: "der", type: "spki" });
}

/**
 * Verify an ``eddsa-jcs-2022`` proof without any ANP dependency.
 *
 * Mirrors `libagentweb.signing.verify_object_proof`: the issuer prefix,
 * assertion-method authorization, published key, signature encoding, and
 * Ed25519 binding are all enforced, and every failure raises
 * `ProofVerificationError`.
 */
export function verifyObjectProof(
  document: Record<string, unknown>,
  options: { issuer: string; controllerDocument: ProofControllerDocument },
): void {
  const value = { ...document };
  const proof = value.proof;
  delete value.proof;
  if (typeof proof !== "object" || proof === null || Array.isArray(proof)) {
    throw new ProofVerificationError("document has no Data Integrity proof");
  }
  const integrity = proof as DataIntegrityProof;
  if (integrity.type !== "DataIntegrityProof") {
    throw new ProofVerificationError("unsupported proof type");
  }
  if (integrity.cryptosuite !== "eddsa-jcs-2022") {
    throw new ProofVerificationError("unsupported proof cryptosuite");
  }
  if (integrity.proofPurpose !== "assertionMethod") {
    throw new ProofVerificationError("proof is not an assertionMethod proof");
  }
  const methodId = integrity.verificationMethod;
  if (
    typeof methodId !== "string" ||
    !methodId.startsWith(`${options.issuer}#`)
  ) {
    throw new ProofVerificationError(
      "proof verification method does not belong to issuer",
    );
  }
  const authorized = new Set(
    (Array.isArray(options.controllerDocument.assertionMethod)
      ? options.controllerDocument.assertionMethod
      : []
    ).map((item) => (typeof item === "string" ? item : item?.id)),
  );
  if (!authorized.has(methodId)) {
    throw new ProofVerificationError(
      "proof verification method is not authorized for assertions",
    );
  }
  const methods = Array.isArray(options.controllerDocument.verificationMethod)
    ? options.controllerDocument.verificationMethod
    : [];
  const method = methods.find((item) => item && item.id === methodId);
  if (!method) {
    throw new ProofVerificationError(
      "proof verification method is not published",
    );
  }
  const proofValue = integrity.proofValue;
  if (typeof proofValue !== "string" || !proofValue.startsWith("z")) {
    throw new ProofVerificationError(
      "proofValue must use base58-btc multibase",
    );
  }
  let signature: Buffer;
  try {
    signature = base58Decode(proofValue.slice(1));
  } catch {
    throw new ProofVerificationError("proofValue is not valid base58-btc");
  }
  if (signature.length !== 64) {
    throw new ProofVerificationError("proofValue is not an Ed25519 signature");
  }
  const proofOptions: Record<string, unknown> = { ...integrity };
  delete proofOptions.proofValue;
  const signingInput = Buffer.concat([
    createHash("sha256")
      .update(Buffer.from(jcsCanonicalize(proofOptions), "utf8"))
      .digest(),
    createHash("sha256")
      .update(Buffer.from(jcsCanonicalize(value), "utf8"))
      .digest(),
  ]);
  let valid = false;
  try {
    const publicKey = multikeyToPublicKey(method.publicKeyMultibase);
    valid = nodeVerify(null, signingInput, publicKey, signature);
  } catch {
    throw new ProofVerificationError(
      "Data Integrity proof signature is invalid",
    );
  }
  if (!valid) {
    throw new ProofVerificationError(
      "Data Integrity proof signature is invalid",
    );
  }
}
